from __future__ import annotations

from pathlib import Path

from openbrep.elicitation_agent import ElicitationState


def ensure_session_defaults(session_state, *, work_dir_default: str | None = None) -> None:
    defaults = {
        "project": None,
        "_import_key_done": "",
        "compile_log": [],
        "compile_result": None,
        "tapir_status": None,
        "tapir_test_trigger": False,
        "tapir_selection_trigger": False,
        "tapir_highlight_trigger": False,
        "tapir_load_params_trigger": False,
        "tapir_apply_params_trigger": False,
        "tapir_selected_guids": [],
        "tapir_selected_details": [],
        "tapir_selected_params": [],
        "tapir_param_edits": {},
        "tapir_last_error": "",
        "tapir_last_sync_at": "",
        "adopted_msg_index": None,
        "_debug_mode_active": None,
        "chat_history": [],
        "chat_history_loaded_work_dir": "",
        "chat_record_history": [],
        "chat_record_history_loaded_work_dir": "",
        "chat_record_browser_open": False,
        "chat_record_open_idx": None,
        "chat_record_delete_idx": None,
        "project_activity_log": [],
        "work_dir": work_dir_default or str(Path.home() / "openbrep-workspace"),
        "agent_running": False,
        "generation_status": "idle",
        "active_generation_id": None,
        "generation_cancel_requested": False,
        "pending_diffs": {},
        "pending_ai_label": "",
        "pending_gsm_name": "",
        "editor_open_path": "",
        "editor_hsf_dir": "",
        "active_hsf_source_dir": "",
        "hsf_save_dialog_open": False,
        "hsf_save_dialog_mode": "",
        "hsf_save_parent_dir": "",
        "hsf_save_name": "",
        "confirm_clear": False,
        "confirm_clear_memory": False,
        "editor_version": 0,
        "_ace_pending_main_editor_keys": set(),
        "script_revision": 0,
        "last_project_snapshot": None,
        "last_project_snapshot_meta": {},
        "last_project_snapshot_label": "",
        "model_api_keys": {},
        "chat_route_mode": "Auto",
        "chat_image_route_mode": "Auto",
        "pro_unlocked": False,
        "pro_license_loaded": False,
        "preview_2d_data": None,
        "preview_3d_data": None,
        "preview_warnings": [],
        "preview_meta": {"kind": "", "timestamp": ""},
        "pending_preview_2d_data": None,
        "pending_preview_3d_data": None,
        "pending_current_preview_2d_data": None,
        "pending_current_preview_3d_data": None,
        "pending_preview_warnings": [],
        "pending_preview_meta": {"kind": "", "timestamp": "", "source": ""},
        "pending_preview_diff_summary": {},
        "pending_compile_result": None,
        "pending_compile_meta": {},
        "assistant_settings": "",
        "elicitation_agent": None,
        "elicitation_state": ElicitationState.IDLE.value,
        "revision_auto_snapshot": False,
        "revision_notice": "",
    }
    for key, value in defaults.items():
        if key not in session_state:
            session_state[key] = value
